# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGvSQfPWu4cS55roRnoI0IeXfvK0mLDX
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
cv2_imshow(rasm1)

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
rasm2=cv2.imread("rasm2.jpg")
rasm3=cv2.imread("rasm3.jpg")
rasm4=cv2.imread("rasm4.jpg")
rasm5=cv2.imread("rasm5.jpg")
cv2_imshow(rasm1)
cv2_imshow(rasm2)
cv2_imshow(rasm3)
cv2_imshow(rasm4)
cv2_imshow(rasm5)

oqqora1=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
oqqora2=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
oqqora3=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
oqqora4=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
oqqora5=cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora1)
cv2_imshow(oqqora2)
cv2_imshow(oqqora3)
cv2_imshow(oqqora4)
cv2_imshow(oqqora5)